### ISSUE TITLE
建议直接发布到 jcenter中央仓库，而不是自己的仓库

### ISSUE THREAD

**Issue by snowdream** [Thereisnospon/CodeView#1]
这样需要自定义仓库位置。

repositories {
    maven {
        url  "http://dl.bintray.com/thereisnospon/maven"
    }
}

**Comment by Thereisnospon** [comment]
一开始尝试过发到 jcenter ,不知道为何经常失败，就先发布了，下次再试试什么原因。现在这样确实不太方便。

**Comment by snowdream** [comment]
我记得加入jcenter就可以了。
你的包名有点不科学，是不是因为这个被拒绝了。
