### ISSUE TITLE
Doesn't work with minifyEnabled (Solved)

### ISSUE THREAD

**Issue by maxx2478** [Thereisnospon/CodeView#17]
Kindly tell the proguard rules for the library.

I've tried 
-keep class thereisnospon.codeview.**{  *; }

but it doesn't work.
Please suggest the proper way and
Thanks for the great library ✌🏻

**Comment by maxx2478** [comment]
I checked the library and found that library uses jsoup.

The solution :
We need to exclude both packages i.e. thereisnospon.codeview as well as org.jsoup

**Comment by Thereisnospon** [comment]
Do you have any other questions

> I checked the library and found that library uses jsoup.
> 
> The solution :
> We need to exclude both packages i.e. thereisnospon.codeview as well as org.jsoup

thanks, do you have any other questions?

**Comment by mahalkarshubham** [comment]
> I checked the library and found that library uses jsoup.
> 
> The solution :
> We need to exclude both packages i.e. thereisnospon.codeview as well as org.jsoup

Can you please provide me some information how to do it and please also provide your proguard code, i ried but it won't worked for me

**Comment by maxx2478** [comment]
> Do you have any other questions
> 
> > I checked the library and found that library uses jsoup.
> > 
> > The solution :
> > We need to exclude both packages i.e. thereisnospon.codeview as well as org.jsoup
> 
> thanks, do you have any other questions?

No. I'll reply him and close this issue.

**Comment by maxx2478** [comment]
> > I checked the library and found that library uses jsoup.
> > 
> > The solution :
> > We need to exclude both packages i.e. thereisnospon.codeview as well as org.jsoup
> 
> Can you please provide me some information how to do it and please also provide your proguard code, i ried but it won't worked for me

copy the below two lines into your proguard rules:

-keep class thereisnospon.codeview.** { *; }

-keep class org.jsoup.** { *; }

the general solution is, you need to exclude external library package, sometimes the external library itself uses other libraries, so you need to check build.gradle of the library for any other libraries if it is using and have to exclude those library's package too.  that's it.
